netty:
  enabled: false
  host: 127.0.0.1
  port: 11286

log:
  error:
    path: "hq-errors/"

database:
  type: sqlite

  sqlite:
    path: "hq-database/sqlite.db"

  mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: hq

forge-support: false
error-log-limit: 5