netty:
  enabled: false
  host: 127.0.0.1
  port: 11286

log:
  error:
    store-limit: 1000
    path: "hq-errors/"

database:
  type: sqlite

  sqlite:
    path: "hq-database/sqlite.db"

  mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: hq

scheduler:
  thread-pool:
    thread-count: 10
    thread-priority: 5

  job-store:
    # cluster 환경이 아닐 경우, false 로 설정 해도 됩니다.
    is-clustered: true
    # JobDataMaps 가 저장될 때 blob 으로 저장되지 않고, key-value 쌍으로 직렬화되어 저장됩니다.
    use-properties: true
    # https://stackoverflow.com/questions/1933676/quartz-java-resuming-a-job-executes-it-many-times
    misfire-threshold: 1100
    # https://stackoverflow.com/questions/14953297/recomended-value-for-org-quartz-jobstore-clustercheckininterval
    cluster-checkin-interval: 2000

forge-support: false