config-version: 1.2

lang: ko_kr

netty:
  enabled: false
  host: 127.0.0.1
  port: 11286

log:
  error:
    store-limit: 1000
    store-path: "hq-errors/"
    print-stack-traces-when-unhandled: false

database:
  # h2, sqlite, mysql
  type: h2
  # 파일 확장자는 붙이지 않습니다.
  file-path: "hq-database/database"

  mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: hq
    maximum-pool-size: 10

scheduler:
  thread-pool:
    thread-count: 10
    thread-priority: 5

  job-store:
    # cluster 환경일 경우, true 로 설정해주세요.
    # SQLite DataSource 일때는 클러스터 환경에서 동작될 수 없기 때문에, false 로 설정되어야 합니다.
    is-clustered: false
    # JobDataMaps 가 저장될 때 blob 으로 저장되지 않고, key-value 쌍으로 직렬화되어 저장됩니다.
    use-properties: true
    # https://stackoverflow.com/questions/1933676/quartz-java-resuming-a-job-executes-it-many-times
    misfire-threshold: 1100
    # https://stackoverflow.com/questions/14953297/recomended-value-for-org-quartz-jobstore-clustercheckininterval
    cluster-checkin-interval: 2000
command:
  tab-complete:
    limit-per-second: 20

forge-support: false