name: Publish to Sonatype Repository

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

env:
  nexusUsername: admin
  nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Prepare Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Publish to Sonatype Repository
      run: gradle publishAllPublicationsToMavenRepository
